### ISSUE TITLE
Rationale for name `.unicodeSets`?

### ISSUE THREAD

**Issue by rauschma** [tc39/proposal-regexp-v-flag#73]
This is how I make sense of the flags `/u` and `/v`:

* Neither `/u` nor `/v`: character sets contain code units.
* `/u`: character sets contain code points.
* `/v`: character sets contain code point sequences.

Where does the name `.unicodeSets` come from? Would a different name better describe what the flag does?

**Comment by mathiasbynens** [comment]
#14
